mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
unified-delay: true
tcp-concurrent: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  respect-rules: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - https://223.5.5.5/dns-query
    - https://120.53.53.53/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    - https://223.5.5.5/dns-query
    - https://120.53.53.53/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '*.localhost'
    - '*.test'
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - lens.l.google.com
    - '*.srv.nintendo.net'
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - '*.*.xboxlive.com'
    - +.msftncsi.com
    - +.msftconnecttest.com
proxies:
  - name: ss-45.63.123.102
    type: ss
    server: 45.63.123.102
    port: 8388
    cipher: 2022-blake3-aes-256-gcm
    password: VyyPNdVzfJUNVWkdEIrZQYwZ69eC6cDc2uKlVQrqRuA=
    udp: true
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - ss-45.63.123.102
      - DIRECT
  - name: Auto
    type: url-test
    proxies:
      - ss-45.63.123.102
    url: https://www.gstatic.com/generate_204
    interval: 300
rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,localhost,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  exclude-interface:
    - tailscale0
  include-uid:
    - 1000
